# Generated by Django 4.1.2 on 2022-10-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0003_remove_user_links_links_userbelongs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='userBelongs',
        ),
        migrations.AddField(
            model_name='user',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.links'),
        ),
    ]
