# Generated by Django 4.1.2 on 2022-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0004_remove_links_userbelongs_user_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='links',
        ),
        migrations.AddField(
            model_name='user',
            name='links',
            field=models.ManyToManyField(to='invoiceapp.links'),
        ),
    ]
