# Generated by Django 4.1.2 on 2022-10-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0007_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
