# Generated by Django 4.1.2 on 2022-10-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0008_links_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
